language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - docker-compose up -d
  - sleep 10

install:
  - pip3 install -r backend/test/requirements.txt

script:
  - python3 backend/test/test.py