language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - docker-compose up -d
  - sleep 10

script:
  - docker ps -a 
