language: python
python:
  - "3.7"

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - sudo apt-get upgrade -y libssl-dev
  - docker-compose up -d
  - sleep 10

install:
  - pip install -r backend/test/requirements.txt

script:
  - python backend/test/server.test.py