version: '3'
services:
## Backend
  backend:
    build:
      context: ./backend  # Ruta al directorio del backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Q1w2e3r4
      - DB_DATABASE=UserDB
    networks:
      - my-network

## Base de datos
  db:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=Q1w2e3r4
    - MYSQL_DATABASE=UserDB
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

 ## Jenkins 
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000
    container_name: jenkins
    volumes:
      - ./infra/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my-network

## Network
networks:
  my-network: